config/routes.rb
Rails.application.routes.draw do
  root to: 'home#new'
  resource :home, controller: :home, only: [:new, :create]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :preload_form
  before_filter :preload_service, only: :create

  def new; end
  
  def create
    if @service.perform
      render text: @service.encrypted_url
    else
      render :new
    end
  end

  private

  def preload_form
    @form = UrlForm.new(params[:form_data])
  end

  def preload_service
    @service = UrlSaver.new(@form)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_form.html.erb
<%= form_for @form, as: :form_data, url: home_path do |form| %>
  
  <% if @form.errors.any? %>
	<div style="error-container">
	  <p class='error-message'><%=  @form.errors.full_messages %></p>
	</div>
  <% end %>

  <%= form.label :url, 'Podaj url' %>
  <%= form.text_field :url, placeholder: 'http://www.google.pl' %>
  <%= form.button 'Skracaj!' %>
<% end %>

app/views/home/new.html.erb
<div class="container">
  <div class="main-container">
    <h1>Skracacz linków.</h1>
    
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>